MainSettings:
  # the y the miner will start mine from
  minHeight: 1

  # The maximum amount of ChunkMiners a player can place at once (integer > than 0)
  maxAmount: 1

  # True = when someone place a ChunkMiner all players with the permission 'chunkminer.notify'
  # receive the message "minerNotifyStaff" (see below in the "Messages" section)
  notify: true

  # What appears in messages instead of "CONSOLE"
  consoleName: "Console"

  # Blocks with the following materials are not removed
  ignoreMaterials:
  - ENDER_CHEST

  # Prevent players from using ChunkMiners in the listed worlds
  blacklistedWorlds:
  - world_without_miners

  # Prevent players from placing miners while they are in one of the listed gamemodes
  # allowed values: CREATIVE - SURVIVAL - ADVENTURE - SPECTATOR
  blockedGamemodes:
  - CREATIVE

  hooks:
    # true = players are not allowed to place chunk miners in protected regions
    WorldGuard: true

    FactionsUUID:
      enabled: true

      allow:
        # Players with one of the listed roles are allowed to place chunk miners in their faction claims.
        # ADMIN, COLEADER, MODERATOR, NORMAL, RECRUIT
        # (if you are using an outdated FactionsUUID version you may not have COLEADER and RECRUIT)
        roles:
        - ADMIN
        - COLEADER
        - MODERATOR

MinerItem:
  # it doesn't have to be a block
  material: COBBLESTONE
  displayName: "&5ChunkMiner"
  lore:
  - ""
  - "&7Right-Click the block you want to"
  - "&7place the &bChunkMiner &7on!"

Messages:
  prefix: "&8[&cChunkMiner&8]"
  HelpMenu:
  - "  &7&m-+-+-+-&r &c&lChunkMiner &7&m-+-+-+-"
  - ""
  - "&b/cminer help &7-> &6Display this menu"
  - "&b/cminer get <amount> &7-> &6Get a chunk miner"
  - "&b/cminer give <target> <amount> &7-> &6Give a ChunkMiner to the target"
  - ""
  - "            &c&m-----+--+-----"

  onlyInGame: "&cThis command can be executed only by a player"
  noCmdPerms: "&cYou do not have permissions to perform this command"
  noPlacePerms: "&cYou are not allowed to place ChunkMiners! &7Missing permission: '{perm}'"
  targetOffline: "&cThe player '{target}' is not online"
  itemGived: "&aYou gave &6{amount}x ChunkMiner &ato &b{target}"
  itemReceivedOther: "&aYou received &6{amount}x &bChunkMiner &afrom &6{giver}"
  itemReceived: "&aYou received &6{amount}x &bChunkMiner"
  minerPlaced: "&aYou placed a &bChunkMiner&a! &7Starting operation..."
  minerSuccess: "&aOperation successfully finished!"
  chunkAlreadyMined: "&cOperation cancelled! This chunk seems to be already mined!"
  minerNotifyStaff: "&7(&4!&7) &a{playerName} placed a ChunkMiner in the world &6{world} &ain the chunk x: &6{x} &az: &6{z}"
  targetFullInventory: "&c{target}'s invantory is full"
  notAllowedGamemode: "&cYou can't place &bChunkMiners &cwhile you are in gamemode &6{gamemode}"
  invalidAmount: "&c'&6{input}&c' is not a valid amount. It must be a positive integer"
  blacklistedWorld: "&cYou are not allowed to place &bChunkMiners &c in this world! &7({world})"
  currentlyProcessed: "&cThere is currently a mining process in this Chunk!"
  maxAmountReached: "&cYou can't place more than &6{max_amount} &bChunkMiners &cat once!"
  notAllowedHereWorldGuard: "&cYou are not allowed to place &bChunkMiners &chere!"
  notAllowedHereFactions: "&cYou are not allowed to place &bChunkMiners &cin this claim!"

# Recommended! The plugin notify you if there is a new update. (Checks only on startup)
CheckForUpdates: true

# DO NOT TOUCH
configVersion: 1.4