main: io.github.spaicygaming.chunkminer.ChunkMiner

name: ChunkMiner
version: ${project.version}
softdepend: [WorldGuard, Factions]

author: SpaicyGaming

commands:
  chunkminer:
    description: Main command.
    aliases: [cminer, miner]